import type { ProductResponse } from "./dto";

export const mockProducts: ProductResponse[] = [
  {
    id: "1",
    userId: "user-1",
    title: "아이폰 13 프로 맥스",
    description: "깨끗하게 사용한 아이폰입니다. 케이스와 액정보호필름 착용했습니다.",
    price: 800000,
    category: "전자제품",
    location: "서울시 강남구",
    imageUrls: ["https://picsum.photos/400/300?random=1"],
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    userId: "user-2",
    title: "에어팟 프로 2세대",
    description: "박스 개봉만 했고 사용 안 했습니다. 새것과 동일합니다.",
    price: 250000,
    category: "전자제품",
    location: "서울시 서초구",
    imageUrls: ["https://picsum.photos/400/300?random=2"],
    status: "active",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "3",
    userId: "user-3",
    title: "유모차 퀴니",
    description: "아이가 커서 더 이상 사용하지 않습니다. 상태 양호합니다.",
    price: 150000,
    category: "육아용품",
    location: "서울시 송파구",
    imageUrls: ["https://picsum.photos/400/300?random=3"],
    status: "active",
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "4",
    userId: "user-4",
    title: "책상 의자 세트",
    description: "이사로 인해 판매합니다. 깨끗하게 관리했습니다.",
    price: 120000,
    category: "가구",
    location: "서울시 마포구",
    imageUrls: ["https://picsum.photos/400/300?random=4"],
    status: "active",
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    updatedAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: "5",
    userId: "user-5",
    title: "나이키 운동화",
    description: "사이즈가 안 맞아서 판매합니다. 신은 적 없습니다.",
    price: 80000,
    category: "의류",
    location: "서울시 강동구",
    imageUrls: ["https://picsum.photos/400/300?random=5"],
    status: "active",
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    updatedAt: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: "6",
    userId: "user-6",
    title: "아이패드 에어 5세대",
    description: "학원 다니면서 사용했는데 이제 필요 없어서 판매합니다.",
    price: 600000,
    category: "전자제품",
    location: "서울시 종로구",
    imageUrls: ["https://picsum.photos/400/300?random=6"],
    status: "active",
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    updatedAt: new Date(Date.now() - 432000000).toISOString(),
  },
  {
    id: "7",
    userId: "user-7",
    title: "유아 장난감 세트",
    description: "아이가 자라서 더 이상 사용하지 않습니다. 깨끗합니다.",
    price: 50000,
    category: "육아용품",
    location: "서울시 영등포구",
    imageUrls: ["https://picsum.photos/400/300?random=7"],
    status: "active",
    createdAt: new Date(Date.now() - 518400000).toISOString(),
    updatedAt: new Date(Date.now() - 518400000).toISOString(),
  },
  {
    id: "8",
    userId: "user-8",
    title: "삼성 노트북",
    description: "업그레이드로 인해 판매합니다. 성능 좋습니다.",
    price: 700000,
    category: "전자제품",
    location: "서울시 노원구",
    imageUrls: ["https://picsum.photos/400/300?random=8"],
    status: "active",
    createdAt: new Date(Date.now() - 604800000).toISOString(),
    updatedAt: new Date(Date.now() - 604800000).toISOString(),
  },
];

export const categories = [
  "전자제품",
  "의류",
  "가구",
  "육아용품",
  "도서",
  "기타",
];

export const locations = [
  "서울시 강남구",
  "서울시 서초구",
  "서울시 송파구",
  "서울시 마포구",
  "서울시 강동구",
  "서울시 종로구",
  "서울시 영등포구",
  "서울시 노원구",
];

